### ISSUE TITLE
Error in Lesson 2, step 2

### ISSUE THREAD

**Issue by trbryant2** [IBM-Bluemix-Docs/terraform#5] opened 2019-02-04 22:05 UTC
I'm trying to provision the environment as directed in this tutorial.  I've tried creating the configuration and I get the following errors when I run the **make infrastructure**   command:
 
Error: Error running plan: 6 error(s) occurred:

* module.bastion.output.bastion_domain: Resource 'ibm_compute_vm_instance.bastion' not found for variable 'ibm_compute_vm_instance.bastion.domain'
* module.bastion.output.bastion_hostname: Resource 'ibm_compute_vm_instance.bastion' not found for variable 'ibm_compute_vm_instance.bastion.hostname'
* module.infranode.output.infra_subnet_id: Resource 'ibm_compute_vm_instance.infranode' not found for variable 'ibm_compute_vm_instance.infranode.0.private_subnet_id'
* module.appnode.output.app_subnet_id: Resource 'ibm_compute_vm_instance.appnode' not found for variable 'ibm_compute_vm_instance.appnode.0.private_subnet_id'
* module.bastion.output.bastion_private_ip: Resource 'ibm_compute_vm_instance.bastion' not found for variable 'ibm_compute_vm_instance.bastion.ipv4_address_private'
* module.bastion.output.bastion_ip_address: Resource 'ibm_compute_vm_instance.bastion' not found for variable 'ibm_compute_vm_instance.bastion.ipv4_address'

make: *** [makefile:3: infrastructure] Error 1

I've attached a screenshot of the errors along with a copy of the variables.tf file. 

Please guide me to how to correct, or where to find additional information.

![lesson2step2](https://user-images.githubusercontent.com/12633074/52240374-45a29880-2896-11e9-906d-55b7940175ec.png)

**Comment by Nadine2016** [comment] 2019-02-22 15:47
closing as the issue is discussed in a different repo

**Closed by Nadine2016** 2019-02-22 15:47 UTC
